using UnityEngine;
using System.Collections;

/*
 * CLASS EmissionRecoil
 * --------------------
 * Uses a force simulated mover to cause a blowback
 * motion away from each emission of the given emitter
 * --------------------
 */ 

public class EmissionRecoil : MonoBehaviour
{
    [SerializeField]
    [Tooltip("Emitter to blow back from")]
    private Emitter2D emitter;
    [SerializeField]
    [Tooltip("Script used to simulate the recoil movement")]
    private ForceSimulatedMover2D mover;
    [SerializeField]
    [Tooltip("Strength of the recoil generated by the emitter")]
    private float recoilStrength;
    // Use this for initialization
    void Start()
    {
        emitter.emissionEvent.AddListener(Recoil);   
    }
    void Recoil(Vector2 forwardForce)
    {
        mover.ApplyForce(-forwardForce, recoilStrength);
    }
}
